default:
  connection:
    singular: 'connection'
    plural: 'connections'
    children:
      connect:
        singular: 'connect'
        plural: 'connects'
  apple:
    another:
      singular: 'another apple'
      plural: 'more apples'
    insideous:
      singular: 'insideous apple'
      plural: 'insideous apples'
0:
  connection:
    singular: 'connection0'
    plural: 'connections0'
    children:
      connect:
        singular: 'connect0'
        plural: 'connects0'