default:
  connection:
    singular: 'connection'
    plural: 'connections'
    children:
      connect:
        singular: 'connect'
        plural: 'connects'
      connecting:
        singular: 'connecting'