default:
  connection:
    singular: 'connection'
    plural: 'connections'
  connect:
    singular: 'connect'
    plural: 'connects'
0:
  connection:
    singular: 'follow'
    plural: 'follows'
  connect:
    singular: 'follow'
    plural: 'follows'