default:
  connection:
    singular: 'connection'
    plural: 'connections'
    children:
      connect:
        singular: 'connect'
        plural: 'connects'
      connecting:
        singular: 'connecting'
0:
  connection:
    singular: 'follower'
    plural: 'followers'
    children:
      connect:
        singular: 'follow'
        plural: 'follows'
      connecting:
        singular: 'following'