development:
    access_key_id: AKIAJIHMXETPW2S76K4A
    secret_access_key: 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
test:
    access_key_id: AKIAJIHMXETPW2S76K4A
    secret_access_key: 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
production:
    access_key_id: AKIAJIHMXETPW2S76K4A
    secret_access_key: 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