production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO

staging:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING