#!/usr/bin/env ruby

# # # # # # # # # # # # #
# Rubber Install Script #
#  Author: Kelly Becker #
# # # # # # # # # # # # #

# Install specific install
system('gem install specific_install')

# Install Rubber
system('gem specific_install -l git://github.com/wr0ngway/rubber.git')

# Bundle Install
system('bundle install && bundle update')