---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: tioki.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger_nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  instance_id: i-d1670ae2
  image_type: m1.small
  image_id: ami-2add531a
  security_groups:
  - tioki_production_default
  - tioki_production_web
  - tioki_production_web_tools
  - tioki_production_production
  - tioki_production_app
  - tioki_production_passenger_nginx
  - tioki_production_db
  external_host: ec2-54-245-28-10.us-west-2.compute.amazonaws.com
  external_ip: 54.245.28.10
  internal_host: ip-10-244-13-170.us-west-2.compute.internal
  internal_ip: 10.244.13.170
  zone: us-west-2c
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
