---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: tioki01
  domain: tioki.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  instance_id: i-41787072
  image_type: m1.small
  image_id: ami-2add531a
  security_groups:
  - tioki_production_default
  - tioki_production_web
  - tioki_production_tioki01
  - tioki_production_app
  - tioki_production_unicorn
  - tioki_production_nginx
  - tioki_production_db
  external_host: ec2-50-112-46-81.us-west-2.compute.amazonaws.com
  external_ip: 50.112.46.81
  internal_host: ip-10-244-163-118.us-west-2.compute.internal
  internal_ip: 10.244.163.118
  zone: us-west-2c
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: www1
  domain: tioki.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  instance_id: i-c9b3adfa
  image_type: m1.small
  image_id: ami-2add531a
  security_groups:
  - tioki_production_default
  - tioki_production_web
  - tioki_production_www1
  - tioki_production_app
  - tioki_production_unicorn
  - tioki_production_nginx
  - tioki_production_db
  external_host: ec2-50-112-90-122.us-west-2.compute.amazonaws.com
  external_ip: 50.112.90.122
  internal_host: ip-10-244-161-216.us-west-2.compute.internal
  internal_ip: 10.244.161.216
  zone: us-west-2c
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
