---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: tioki.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger_nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: false
  instance_id: i-f52b41c6
  image_type: m1.small
  image_id: ami-2add531a
  security_groups:
  - tioki_production_default
  - tioki_production_web
  - tioki_production_app01
  - tioki_production_app
  - tioki_production_passenger_nginx
  - tioki_production_db
  external_host: ec2-50-112-61-155.us-west-2.compute.amazonaws.com
  external_ip: 50.112.61.155
  internal_host: ip-10-248-88-13.us-west-2.compute.internal
  internal_ip: 10.248.88.13
  zone: us-west-2a
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
