---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: staging
  domain: tioki.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger_nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options: {}
  instance_id: i-0bd58c38
  image_type: m1.small
  image_id: ami-2add531a
  security_groups:
  - tioki_staging_default
  - tioki_staging_web
  - tioki_staging_staging
  - tioki_staging_app
  - tioki_staging_passenger_nginx
  - tioki_staging_db
  external_host: ec2-54-245-46-58.us-west-2.compute.amazonaws.com
  external_ip: 54.245.46.58
  internal_host: ip-10-249-20-177.us-west-2.compute.internal
  internal_ip: 10.249.20.177
  zone: us-west-2a
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
