---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: unicorn
  domain: tioki.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  instance_id: i-733b3240
  image_type: m1.small
  image_id: ami-2add531a
  security_groups:
  - tioki_staging_default
  - tioki_staging_web
  - tioki_staging_unicorn
  - tioki_staging_app
  - tioki_staging_nginx
  - tioki_staging_haproxy
  - tioki_staging_db
  external_host: ec2-50-112-64-173.us-west-2.compute.amazonaws.com
  external_ip: 50.112.64.173
  internal_host: ip-10-244-26-237.us-west-2.compute.internal
  internal_ip: 10.244.26.237
  zone: us-west-2c
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
