---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: www2
  domain: tioki.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  instance_id: i-4a06d978
  image_type: m1.medium
  image_id: ami-2add531a
  security_groups:
  - tioki_production_default
  - tioki_production_web
  - tioki_production_www2
  - tioki_production_unicorn
  - tioki_production_nginx
  - tioki_production_haproxy
  - tioki_production_app
  - tioki_production_db
  external_host: ec2-50-112-192-215.us-west-2.compute.amazonaws.com
  external_ip: 50.112.192.215
  internal_host: ip-10-244-12-109.us-west-2.compute.internal
  internal_ip: 10.244.12.109
  zone: us-west-2c
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: www1
  domain: tioki.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: cramp
    options: {}
  instance_id: i-12f92020
  image_type: m1.medium
  image_id: ami-2add531a
  security_groups:
  - tioki_production_default
  - tioki_production_web
  - tioki_production_www1
  - tioki_production_unicorn
  - tioki_production_nginx
  - tioki_production_haproxy
  - tioki_production_app
  - tioki_production_db
  - tioki_production_cramp
  external_host: ec2-54-245-7-197.us-west-2.compute.amazonaws.com
  external_ip: 54.245.7.197
  internal_host: ip-10-244-26-114.us-west-2.compute.internal
  internal_ip: 10.244.26.114
  zone: us-west-2c
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
