---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: www1
  domain: tioki.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: !ruby/string:HighLine::String |-
      d2Vi
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: solr
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: cramp
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: !ruby/string:HighLine::String |-
      ZGI=
    options:
      !ruby/string:HighLine::String "cHJpbWFyeQ==": true
  instance_id: i-fdf7f8c9
  image_type: m1.medium
  image_id: ami-2add531a
  security_groups:
  - tioki_production_default
  - tioki_production_web
  - tioki_production_www1
  - tioki_production_unicorn
  - tioki_production_nginx
  - tioki_production_haproxy
  - tioki_production_db
  - tioki_production_app
  - tioki_production_solr
  - tioki_production_cramp
  external_host: ec2-54-214-198-102.us-west-2.compute.amazonaws.com
  external_ip: 54.214.198.102
  internal_host: ip-10-245-124-45.us-west-2.compute.internal
  internal_ip: 10.245.124.45
  zone: us-west-2c
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
