---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: www1
  domain: tioki.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: cramp
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: solr
    options: {}
  instance_id: i-7ffcb34b
  image_type: m1.medium
  image_id: ami-2add531a
  security_groups:
  - tioki_production_default
  - tioki_production_web
  - tioki_production_www1
  - tioki_production_unicorn
  - tioki_production_nginx
  - tioki_production_haproxy
  - tioki_production_app
  - tioki_production_db
  - tioki_production_cramp
  external_host: ec2-54-202-3-133.us-west-2.compute.amazonaws.com
  external_ip: 54.202.3.133
  internal_host: ip-10-245-83-82.us-west-2.compute.internal
  internal_ip: 10.245.83.82
  zone: us-west-2c
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
