---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: unicorn01
  domain: tioki.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: tools
    options: {}
  instance_id: i-591b146a
  image_type: m1.small
  image_id: ami-2add531a
  security_groups:
  - tioki_staging_default
  - tioki_staging_web
  - tioki_staging_unicorn01
  - tioki_staging_app
  - tioki_staging_unicorn
  - tioki_staging_nginx
  - tioki_staging_db
  - tioki_staging_tools
  external_host: ec2-54-245-10-217.us-west-2.compute.amazonaws.com
  external_ip: 54.245.10.217
  internal_host: ip-10-244-25-140.us-west-2.compute.internal
  internal_ip: 10.244.25.140
  zone: us-west-2c
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
