#####################################
# Install Ubuntu Ruby 1.9.1 (1.9.3) #
#####################################
packages: [build-essential, git-core, subversion, curl, autoconf, bison, ruby1.9.1, zlib1g-dev, libssl-dev, libreadline6-dev, libxml2-dev, libyaml-dev]